# Generated by Django 5.1.4 on 2024-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
