# Generated by Django 5.1.3 on 2024-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author')], default='reader', max_length=10),
        ),
    ]
