# Generated by Django 5.1.3 on 2024-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_review_likes_alter_reviewlike_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
