# Generated by Django 5.1.3 on 2024-12-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_address_and_more'),
        ('api', '0015_review_dislikes_count_review_likes_count'),
    ]

    operations = [
    ]
