# Generated by Django 5.1.3 on 2024-12-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20241217_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
