# Generated by Django 5.1.3 on 2024-12-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclub',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookclubmembership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RenameField(
            model_name='bookclubmembership',
            old_name='role',
            new_name='m_type',
        ),
    ]
