# Generated by Django 5.1.3 on 2024-12-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_bookclubmembership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclubdiscussion',
            name='book_club',
        ),
        migrations.RemoveField(
            model_name='bookclubmembership',
            name='book_club',
        ),
        migrations.RemoveField(
            model_name='bookclubdiscussion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookclubmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookClub',
        ),
        migrations.DeleteModel(
            name='BookClubDiscussion',
        ),
        migrations.DeleteModel(
            name='BookClubMembership',
        ),
    ]
