# Generated by Django 5.1.3 on 2024-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_clubpost_created_at_remove_clubpost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookclub',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='book_clubs', to='api.tag'),
        ),
    ]
