# Generated by Django 5.1.3 on 2024-12-20 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userprofile_bio_followings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_bookclub_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_club_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('club_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.clubpost')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.bookclubpost')),
            ],
        ),
    ]
