# Generated by Django 5.1.3 on 2024-12-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_bookclubpost_likes_clubpost_likes_postreply'),
        ('api', '0027_readingprogress'),
    ]

    operations = [
    ]
