name: Django Backend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Set DJANGO_SETTINGS_MODULE for testing
      - name: Set DJANGO_SETTINGS_MODULE for testing
        run: echo "DJANGO_SETTINGS_MODULE=bookies.settings" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookies/requirements.txt

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for database..."
            sleep 2
          done

      # Apply migrations
      - name: Apply migrations
        run: |
          cd bookies  # Ensure you're in the correct folder
          python manage.py makemigrations --check
          python manage.py migrate
        env:
          GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DJANGO_SETTINGS_MODULE: bookies.settings

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          cd bookies
          pytest -v --cov=bookies/api
        env:
          GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DJANGO_SETTINGS_MODULE: bookies.settings
